### ISSUE TITLE
Temperature Offset

### ISSUE THREAD

**Issue by houleyh** [HubitatCommunity/AeotecMultiSensor6#3]
Is there an issue with the Temperature offset parameter.  No mather what value is there, my dashboard's value never changes.  Please help.  yhoule64@gmail.com

**Comment by csteele-PD** [comment]
I am unable to detect a problem.

I have a MultiSensor 6 and it's offset was 0 and the temp displayed is 71.4 F. I changed the offset to be 100 (10.0 degrees) and the next temp message arrived with a value of 81.5.  (Since the temp can 'jitter' I selected a 10 degree offset to make the functionality very clear.)

![Screen Shot 2021-04-07 at 7 45 09 AM](https://user-images.githubusercontent.com/18298751/113886796-cfe82f00-9775-11eb-99b4-dfa0f6185b74.png)
![Screen Shot 2021-04-07 at 7 45 19 AM](https://user-images.githubusercontent.com/18298751/113886801-d080c580-9775-11eb-990e-1e6457bb0bed.png)
![Screen Shot 2021-04-07 at 7 45 52 AM](https://user-images.githubusercontent.com/18298751/113886804-d1195c00-9775-11eb-9af1-c9c4d032aad3.png)

Note that it is the Multisensor that is doing all the work. The Driver simply takes the human entered offset and pushes it to the Multisensor. The Multisensor is the one that "does the math." The next temperature report will be "after the math." Thus, make sure you're using 1/10ths and that you wait long enough for the offset message to get to the Multisensor, and one temperature report after the offset message. My test Multisensor 6 is on USB power and thus for me, there's no wait for wakeup. For a battery powered Multisensor, it might be a minute before it wakes and allows the offset message to be sent. THEN it will start doing the math.

**Comment by houleyh** [comment]
Thanks for the reply,

The behavior of my sensor is strange.  Those offsets, are they absolute or
relative? Meaning if I go 10 degrees up (100) and then I want to switch it
back to normal....do I do 0 or -100?

I run on batteries.  It's like if it sometimes works and sometimes not.
Bizarre.  Thanks.

Here is what I have.  The temp should be around 78..

Commands

Configure
configure

Get Parameter Report
getParameterReport
parameterNumber :

Refresh
refresh

Set Parameter
setParameter
parameterNumber :
size :
value :
Current States

   - acceleration : *inactive*
   - battery : *100*
   - humidity : *52*
   - illuminance : *16*
   - motion : *inactive*
   - tamper : *clear*
   - temperature : *87.4*
   - ultravioletIndex : *0*

State Variables

   - Status : *Current*
   - batteryRuntimeStart : *1617815009768*
   - lastRefresh : *1617815076285*
   - realLuminance : *2378*
   - enableDebugging : *true*
   - InternalName : *AeotecMultiSensor6_2*
   - lastBatteryReport : *1617824931401*
   - sensorTemp : *78.2*
   - wakeInterval : *3600*
   - Copyright : *© 2019 C Steele -- v2.0.1*
   - realTemperature : *81.8*
   - needfwUpdate :
   - currentProperties : *{44=[10], 45=[2], 252=[0], 111=[0, 0, 14, 16],
   101=[0, 0, 0, 241], 3=[0, 240], 4=[5], 5=[1], 8=[30], 81=[0], 40=[0],
   41=[0, 20, 2, 0], 42=[10], 43=[0, 100]}*
   - tempOffset : *-75.0*
   - realUV : *0*
   - realHumidity : *39*
   - firmware : *1.14*
   - UpdateInfo : *12/28/2020*





Yvan Houle
***@***.***



Le mer. 7 avr. 2021, à 10 h 54, c steele ***@***.***> a
écrit :

**Comment by houleyh** [comment]
Hi,

My Aeotec Multi 6 just does not react to the Preferences I try to push in.
I put offsets (Both Temp and Humidity) and then...no change.  I put a
second battery, still at 50% power 1 hour after.  It's like if there is no
communication back and forth other than Temperatures and humidity changes
that seem to be ok (Need a light offset but I just can't).
Do you think I have a defective unit?

Thanks for your help.


    Yvan Houle
***@***.***



Le mer. 7 avr. 2021, à 10 h 54, c steele ***@***.***> a
écrit :

**Comment by csteele-PD** [comment]
The manual for this can be found online and I looked at this one:

http://manuals-backend.z-wave.info/make.php?lang=en&sku=AEOEZW100&cert=ZC10-16065113

I looked specifically for the Wake process but was reminded there is a "Health" test available too:

![Screen Shot 2021-04-11 at 8 48 35 AM](https://user-images.githubusercontent.com/18298751/114311268-ead2e000-9aa2-11eb-87d5-56911c1493a9.png)
